# Generated by Django 3.0 on 2019-12-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type_id', models.CharField(max_length=20)),
                ('publisher_id', models.CharField(max_length=100)),
                ('desplay_text', models.CharField(max_length=100)),
                ('publisher_name', models.CharField(max_length=100)),
                ('offer_type_name', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10)),
                ('version', models.IntegerField()),
                ('change_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upn', models.CharField(max_length=100)),
                ('scope', models.CharField(max_length=100)),
                ('publisher_name', models.CharField(max_length=100)),
                ('role_name', models.CharField(max_length=20)),
                ('role_type', models.CharField(max_length=20)),
                ('manageable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('publisher_id', models.CharField(max_length=50)),
                ('display_text', models.CharField(max_length=100)),
                ('microsoft_partner_network_id', models.IntegerField()),
                ('public_publisher_id', models.CharField(max_length=100)),
                ('legacy_publisher_id', models.CharField(max_length=100)),
                ('expired_time', models.DateField()),
                ('changed_time', models.DateField()),
            ],
        ),
    ]
