# Generated by Django 3.0 on 2019-12-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_offer_offer_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='change_time',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='changed_time',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='expired_time',
            field=models.CharField(max_length=30),
        ),
    ]
