# Generated by Django 3.0 on 2019-12-19 01:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191212_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='desplay_text',
            new_name='display_text',
        ),
        migrations.AddField(
            model_name='offer',
            name='offerid',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
